---
- name: "Updating the guest operating system."
  apt:
    force_apt_get: true
    name: "*"
    state: latest     # noqa package-latest
    update_cache: "yes"
- name: "Installing additional packages."
  apt:
    name:
      - bash-completion
      - curl
      - wget
      - git
      - net-tools
      - unzip
      - ca-certificates
      - vim 
      - resolvconf
      - rsync
      - docker.io
      - cloud-init
      - locales-all
      - nfs-client
    state: latest     # noqa package-latest
