# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: "Prepare the {{ ansible_facts['distribution'] }} guest operating system."
  include_tasks: "{{ ansible_facts['distribution'] | lower }}.yml"
  when: "ansible_facts['distribution'] == 'Debian'"
